version: '3.8'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_HOST: db
      DB_NAME: '${DB_DATABASE}'
    depends_on: 
      - db
  
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
        - '3306:3306'